apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: glusterfs-client
  labels:
    app: glusterfs-client
spec:
  template:
    metadata:
      labels:
        name: glusterfs-client
    spec:
      nodeSelector:
        ndslabs-role: compute
      # Do we need either of these?
      # hostPID: true
      # hostIPC: true
      hostNetwork: true
      containers:
        - image: ndslabs/gluster:test
          name: glusterfs-client
          command:
            - "client 192.168.100.89"
          securityContext:
            privileged: true
          volumeMounts:
            - name: hostroot
              mountPath: /hostroot
            - name: glfs
              mountPath: /var/glfs
      volumes:
        - name: hostroot
          hostPath:
              path: /
        - name: glfs
          hostPath:
              path: /var/glfs
