apiVersion: v1
kind: Service
metadata:
  name: glfs-server1
  labels:
    app: glfs-server1
spec:
  ports:
    - port: 24007
  selector:
    app: glfs-server1
---
apiVersion: v1
kind: Service
metadata:
  name: glfs-server2
  labels:
    app: glfs-server2
spec:
  ports:
    - port: 24007
  selector:
    app: glfs-server2
